name: Workflow

on:
  push:

jobs:
  job1:
    uses: ./.github/workflows/workflow-a.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "Value is ${{needs.job1.outputs.foo}}"

  call-workflow-b:
    needs: job1
    uses: ./.github/workflows/workflow-b.yml
    with:
      foo: ${{ needs.job1.outputs.foo }}
