# name: Workflow

# on:
#   push:

# jobs:
#   call-workflow-a:
#     uses: ./.github/workflows/workflow-a.yml

#   call-workflow-b:
#     needs: call-workflow-a
#     uses: ./.github/workflows/workflow-b.yml
#     with:
#       foo: ${{ needs.call-workflow-a.outputs.foo }}

name: Workflow

on:
  push:

jobs:
  call-workflow-a:
    uses: ./.github/workflows/workflow-a.yml

  print-directly:
    runs-on: ubuntu-latest
    needs: call-workflow-a
    steps:
      - name: print
        run: |
          echo "Foo is ${{ needs.call-workflow-a.outputs.foo }}"

  call-workflow-b:
    needs: call-workflow-a
    uses: ./.github/workflows/workflow-b.yml
    with:
      foo: ${{ needs.call-workflow-a.outputs.foo }}
