name: Workflow B

on:
  workflow_call:
    inputs:
      foo:
        type: string
        required: true

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Output foo
        run: echo "Foo is ${{ inputs.foo }}"
