# .github/workflows/workflow-a.yml
name: workflow-a

on:
  workflow_call:

jobs:
  generate-output:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: set-output-step
        run: echo "foo=42" >> $GITHUB_OUTPUT

    outputs:
      foo: ${{ steps.set-output-step.outputs.foo }}
