# .github/workflows/workflow-b.yml
name: workflow-b

on:
  workflow_call:
    inputs:
      foo:
        type: string
        description: "Value of foo to print"
        required: true

jobs:
  print-input:
    runs-on: ubuntu-latest
    steps:
      - name: Print foo
        run: |
          echo "Foo value is: ${{ inputs.foo }}"
